#!/usr/bin/env bash

if [ -f "./bin/standup.sh" ]; then
    ./bin/standup.sh
fi

agy "$@"

if [ -f "./bin/standdown.sh" ]; then
    ./bin/standdown.sh
fi

if [ -f "./bin/status" ]; then
    ./bin/status
fi
